sudo: required
services:
  - docker

before_install:
  - docker build -t nersesyan/docker-react -f Dockerfile.dev .

script:
  - docker run nersesyan/docker-react yarn test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-471112571774"
  bucket_path: "frontend"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"